routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth'])->name('dashboard');

require __DIR__.'/auth.php';

Route::get('accounts/{id}/inbox/{uid}', [\App\Http\Controllers\AccountController::class, 'inbox'])->name('accounts.inbox');
Route::resource('accounts', \App\Http\Controllers\AccountController::class);

app/Models/Account.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Account extends Model
{
    use HasFactory;

    protected $fillable = ['type', 'username', 'password', 'recovery', 'is_read', 'is_active', 'last_id'];

    protected $appends =  ['has_inbox'];

    public function inboxes()
    {
        return $this->hasMany(Inbox::class)->orderByDesc('uid');
    }

    public function getHasInboxAttribute()
    {
        return !!$this->inboxes()->where('is_read', 0)->count();
    }
}

app/Http/Controllers/AccountController.php
<?php

namespace App\Http\Controllers;

use App\Criteria\AccountAccessibleCriteria;
use App\Http\Controllers\Controller;
use App\Repositories\InboxRepository;
use Illuminate\Http\Request;
use Prettus\Validator\Exceptions\ValidatorException;
use App\Repositories\AccountRepository;

/**
 * Class AccountsController.
 *
 * @package namespace App\Http\Controllers;
 */
class AccountController extends Controller
{
    /**
     * @var AccountRepository
     */
    protected $repository;
    /**
     * @var InboxRepository
     */
    private $inboxRepository;


    /**
     * AccountsController constructor.
     *
     * @param AccountRepository $repository
     */
    public function __construct(AccountRepository $repository, InboxRepository $inboxRepository)
    {
        $this->repository = $repository;
        $this->inboxRepository = $inboxRepository;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $accounts = $this->repository->paginate();

        return view('accounts.index', compact('accounts'));
    }

    /**
     * Create the specified resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('accounts.create_edit');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param Request $request
     * @return \Illuminate\Http\Response
     *
     */
    public function store(Request $request)
    {
        try {
            $account = $this->repository->create($request->all());
            $response = [
                'message' => 'Account created.',
                'data' => $account->toArray(),
            ];
            return redirect()->route('accounts.index')->with('message', $response['message']);
        } catch (ValidatorException $e) {
            return redirect()->back()->withErrors($e->getMessageBag())->withInput();
        }
    }

    /**
     * Display the specified resource.
     *
     * @param int $id
     *
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $account = $this->repository->with('inboxes')->find($id);
        $inboxes = $this->inboxRepository
            ->pushCriteria(new AccountAccessibleCriteria($id))
            ->orderBy('uid', 'desc')
            ->paginate();
        return view('accounts.show', compact('account', 'inboxes'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param int $id
     *
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $account = $this->repository->find($id);

        return view('accounts.create_edit', compact('account'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param Request $request
     * @param string $id
     *
     * @return \Illuminate\Http\RedirectResponse
     */
    public function update(Request $request, $id)
    {
        try {
            $account = $this->repository->update($request->all(), $id);

            $response = [
                'message' => 'Account updated.',
                'data' => $account->toArray(),
            ];

            return redirect()->back()->with('message', $response['message']);
        } catch (ValidatorException $e) {
            return redirect()->back()->withErrors($e->getMessageBag())->withInput();
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param int $id
     *
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $this->repository->update(['status' => -1], $id);

        return redirect()->back()->with('message', 'Account deleted.');
    }

    public function inbox($id, $uid)
    {
        $account = $this->repository->with('inboxes')->find($id);
        $inbox = $this->inboxRepository
            ->pushCriteria(new AccountAccessibleCriteria($id))
            ->find($uid);
        $inbox->is_read = 1;
        $inbox->save();
        return view('accounts.inbox', compact('account', 'inbox'));
    }
}

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.app');
    }
}

resources/views/accounts/create_edit.blade.php
<x-app-layout>
    <x-slot name="header">
        <div class="lg:flex lg:items-center lg:justify-between">
            <div class="flex-1 min-w-0">
                <h2 class="font-semibold text-xl text-gray-800 leading-tight">
                    Create New User
                </h2>
            </div>
        </div>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 bg-white border-b border-gray-200">
                    <!-- Validation Errors -->
                    <x-auth-validation-errors class="mb-4" :errors="$errors" />

                    @if(isset($account))
                        <form method="POST" action="{{ route('accounts.update', [$account->id]) }}">
                        @method('PUT')
                    @else
                        <form method="POST" action="{{ route('accounts.store') }}">
                    @endif

                    @csrf
                        <div>
                            <x-label for="username" value="Username" />
                            <x-input id="username" class="w-full" type="text" name="username" :value="old('username', isset($account) ? $account->username : null)"/>
                        </div>
                        <div>
                            <x-label for="password" value="Password" />
                            <x-input id="password" class="w-full" type="text" name="password" :value="old('password', isset($account) ? $account->password : null)"/>
                        </div>
                        <div class="mt-4">
                            <x-label for="is_active" value="Status" />
                            <x-select id="is_active" name="is_active" :options="[1 => 'Enable', 0 => 'Disable']" :value="old('is_active', isset($account) ? $account->is_active : 1)"></x-select>
                        </div>
                        <div class="flex items-center justify-end mt-4">
                            <a href="{{ route('accounts.index') }}">
                                <x-button type="button" class="text-white bg-indigo-600">
                                    Hủy
                                </x-button>
                            </a>
                            <x-button class="ml-3">
                                {{ isset($account) ? 'Cập Nhật' : 'Thêm Mới' }}
                            </x-button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</x-app-layout>

resources/views/accounts/inbox.blade.php
<x-app-layout>
    <x-slot name="header">
        <div class="lg:flex lg:items-center lg:justify-between">
            <div class="flex-1 min-w-0">
                <h2 class="font-semibold text-xl text-gray-800 leading-tight">
                    Inbox
                </h2>
            </div>
            <div class="mt-5 flex lg:mt-0 lg:ml-4">
                <x-link href="{{ route('accounts.show', $account->id) }}">
                    Back
                </x-link>
            </div>
        </div>
    </x-slot>

    <div class="py-5">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white shadow overflow-hidden sm:rounded-lg">
                <div class="px-4 py-5 sm:px-6">
                    <h3 class="text-lg leading-6 font-medium text-gray-900">
                        {{ $inbox->subject }}
                    </h3>
                </div>
                <div class="shadow overflow-hidden border-b border-gray-200 sm:rounded-lg table-responsive">
                    {!! $inbox->body !!}
                </div>
            </div>
        </div>
    </div>
</x-app-layout>

resources/views/accounts/index.blade.php
<x-app-layout>
    <x-slot name="header">
        <div class="lg:flex lg:items-center lg:justify-between">
            <div class="flex-1 min-w-0">
                <h2 class="font-semibold text-xl text-gray-800 leading-tight">
                    Người Dùng
                </h2>
            </div>
            <div class="mt-5 flex lg:mt-0 lg:ml-4">
                <x-link href="{{ route('accounts.create') }}">
                    Thêm Mới
                </x-link>
            </div>
        </div>
    </x-slot>

    <div class="py-5">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="shadow overflow-hidden border-b border-gray-200 sm:rounded-lg table-responsive">
                <table class="min-w-full divide-y divide-gray-200">
                    <thead class="bg-gray-50">
                    <tr>
                        <th scope="col"
                            class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                            Tên
                        </th>
                        <th scope="col"
                            class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                            Email
                        </th>
                        <th scope="col"
                            class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                            Trạng Thái
                        </th>
                        <th scope="col"
                            class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                            Ngày Tham Gia
                        </th>
                        <th scope="col" class="relative px-6 py-3">
                            <span class="sr-only">Edit</span>
                        </th>
                    </tr>
                    </thead>
                    <tbody class="bg-white divide-y divide-gray-200">
                    @if(!$accounts->isEmpty())
                        @foreach($accounts as $account)
                            <tr>
                                <td class="px-6 py-4 whitespace-nowrap">
                                    <a href="{{ route('accounts.show', [$account->id]) }}" class="text-indigo-600 hover:text-indigo-900">
                                        #{{ $account->id }} - {{ $account->username }}
                                    </a>
                                </td>
                                <td class="px-6 py-4 whitespace-nowrap">
                                    {{ $account->password }}
                                </td>
                                <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                                    @if ($account->has_inbox)
                                        <span class="px-2 inline-flex text-xs leading-5 font-semibold rounded-full bg-green-100 text-green-800">
                                      Unread
                                    </span>
                                    @else
                                        <span class="px-2 inline-flex text-xs leading-5 font-semibold rounded-full bg-red-100 text-red-800">
                                      Read
                                    </span>
                                    @endif
                                </td>
                                <td class="px-6 py-4 whitespace-nowrap">
                                    {{ $account->created_at }}
                                </td>
                                <td class="px-6 py-4 whitespace-nowrap text-right text-sm font-medium">
                                    <form method="POST" action="{{ route('accounts.destroy', $account->id) }}">
                                        @method('DELETE')
                                        @csrf
                                        <a href="{{ route('accounts.edit', [$account->id]) }}" class="text-indigo-600 hover:text-indigo-900">Sửa</a> |
                                        <button type="submit">Xóa</button>
                                    </form>
                                </td>
                            </tr>
                        @endforeach
                    @else
                        <tr>
                            <td colspan="5" class="px-6 py-4 whitespace-nowrap">
                                Chưa có tài khoản nào
                            </td>
                        </tr>
                    @endif
                    <!-- More people... -->
                    </tbody>
                </table>
                <div class="mt-4">
                    {{ $accounts->links() }}
                </div>
            </div>
        </div>
    </div>
</x-app-layout>

resources/views/accounts/show.blade.php
<x-app-layout>
    <x-slot name="header">
        <div class="lg:flex lg:items-center lg:justify-between">
            <div class="flex-1 min-w-0">
                <h2 class="font-semibold text-xl text-gray-800 leading-tight">
                    Inbox
                </h2>
            </div>
            <div class="mt-5 flex lg:mt-0 lg:ml-4">
                <x-link href="{{ route('accounts.index') }}">
                    Back
                </x-link>
            </div>
        </div>
    </x-slot>

    <div class="py-5">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="shadow overflow-hidden border-b border-gray-200 sm:rounded-lg table-responsive">
                <table class="min-w-full divide-y divide-gray-200">
                    <thead class="bg-gray-50">
                    <tr>
                        <th scope="col"
                            class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                            Tên
                        </th>
                        <th scope="col"
                            class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                            Email
                        </th>
                        <th scope="col"
                            class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                            Trạng Thái
                        </th>
                        <th scope="col"
                            class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                            Ngày Tham Gia
                        </th>
                        <th scope="col" class="relative px-6 py-3">
                            <span class="sr-only">Edit</span>
                        </th>
                    </tr>
                    </thead>
                    <tbody class="bg-white divide-y divide-gray-200">
                    @if(!$inboxes->isEmpty())
                        @foreach($inboxes as $inbox)
                            <tr>
                                <td class="px-6 py-4 whitespace-nowrap">
                                    #{{ $inbox->id }} - {{ $inbox->folder }}
                                </td>
                                <td class="px-6 py-4 whitespace-nowrap">
                                    {{ $inbox->subject }}
                                </td>
                                <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                                    @if (!$inbox->is_read)
                                        <span class="px-2 inline-flex text-xs leading-5 font-semibold rounded-full bg-green-100 text-green-800">
                                      Unread
                                    </span>
                                    @else
                                        <span class="px-2 inline-flex text-xs leading-5 font-semibold rounded-full bg-red-100 text-red-800">
                                      Read
                                    </span>
                                    @endif
                                </td>
                                <td class="px-6 py-4 whitespace-nowrap">
                                    {{ $inbox->mail_at }}
                                </td>
                                <td class="px-6 py-4 whitespace-nowrap text-right text-sm font-medium">
                                    <a href="{{ route('accounts.inbox', [$account->id, $inbox->id]) }}" class="text-indigo-600 hover:text-indigo-900">Read</a>
                                </td>
                            </tr>
                        @endforeach
                    @else
                        <tr>
                            <td colspan="5" class="px-6 py-4 whitespace-nowrap">
                                Chưa có tài khoản nào
                            </td>
                        </tr>
                    @endif
                    <!-- More people... -->
                    </tbody>
                </table>
                <div class="mt-4">
                    {{ $inboxes->links() }}
                </div>
            </div>
        </div>
    </div>
</x-app-layout>